//
// Created by kooltew on 5/11/2021.
//

#ifndef KB_KNAPSACK_PARTITION_SOLUTION_KNAPSACK_GREEDY_TOP_DOWN_SOLVER_H
#define KB_KNAPSACK_PARTITION_SOLUTION_KNAPSACK_GREEDY_TOP_DOWN_SOLVER_H

#endif //KB_KNAPSACK_PARTITION_SOLUTION_KNAPSACK_GREEDY_TOP_DOWN_SOLVER_H
